apiVersion: apps/v1
kind: Deployment
metadata:
  name: exploravis-ui
  namespace: exploravis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exploravis-ui
  template:
    metadata:
      labels:
        app: exploravis-ui
    spec:
      automountServiceAccountToken: false
      containers:
      - name: exploravis-ui
        image: ghcr.io/exploravis/exploravis-ui:latest
        ports:
        - containerPort: 3000
        env:
          - name: VITE_API_URL
            value: "http://heheh:8088"
---
apiVersion: v1
kind: Service
metadata:
  name: exploravis-ui
  namespace: exploravis
spec:
  type: ClusterIP
  selector:
    app: exploravis-ui
  ports:
  - port: 3000 
    targetPort: 3000
    name: http
