apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner-worker
  namespace: exploravis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scanner-worker
  template:
    metadata:
      labels:
        app: scanner-worker
    spec:
      securityContext:
        runAsUser: 0 

      containers:
      - name: scanner-worker
        image: ghcr.io/exploravis/scanner-worker:latest
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"

        securityContext:
          capabilities:
            add: ["NET_RAW", "NET_ADMIN"]
