name: Build & Publish exploravis core images

on:
  push:
    branches:
      - main
    tags:
      - 'v*' 

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # LATER
      # - name: Login to Docker Hub (optional)
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push API Server 
        uses: docker/build-push-action@v5
        with:
          context: ./orchestrator
          push: true
          tags: |
            ${{ github.repository_owner | lower }}/orchestrator:latest
            ghcr.io/${{ github.repository_owner | lower }}/orchestrator:latest
            ${{ github.repository_owner | lower}}/orchestrator:${{ github.sha }}
            ghcr.io/${{ github.repository_owner | lower}}/orchestrator:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ github.event.repository.updated_at }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=MIT

      - name: Build and Push scanner-worker 
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          file: ./worker/scanner-worker/Dockerfile
          push: true
          tags: |
            ${{ github.repository_owner | lower }}/scanner-worker:latest
            ghcr.io/${{ github.repository_owner | lower }}/scanner-worker:latest
            ${{ github.repository_owner | lower }}/scanner-worker:${{ github.sha }}
            ghcr.io/${{ github.repository_owner | lower }}/scanner-worker:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ github.event.repository.updated_at }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=MIT
